[tool.black]
line-length = 88
exclude = ['.venv', 'venv', 'node_modules', 'build']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "W", "C", "BLK", "ANN"]
ignore = ["E203", "W503"]
